### ISSUE TITLE
Bot is down

### ISSUE THREAD

**Issue by KnorpelSenf** [SijmenSchoon/regexbot#18]
Sad day. Me sad. No regex bot. Why. Server issues? Can restart? Financial issues? Need someone to take over? Help is there. Please bring it back? Then me good again.

**Comment by KnorpelSenf** [comment]
I don't know why I said it like that

**Comment by vijfhoek** [comment]
It indeed went down overnight, but I brought it back about an hour ago

**Comment by KnorpelSenf** [comment]
Indeed! Thank you so much!
